### ISSUE TITLE
Tab labels dissapearing on iPadOS -

### ISSUE THREAD

**Issue by PossiblyPeso** [mozilla-mobile/firefox-ios#13462]
## Steps to reproduce
Open Firefox on iPadOS
Open >1 tab

### Expected behavior
Should be able to see the text normally shown in the tab
### Actual behavior
Tab appears completely blank save for the close tab symbol
### Device & build information
* Device : iPad Pro 12.9 5th gen, iPadOS 16.3.1 
* Build version:  110.1 (28420) 
* First seen version: 109 or 110 (can't actually remember) 
### Notes
EDIT
a restart of the ipad fixed the issue, so not sure now if it was Firefox or my iPad that glitched

**EDIT 2**
**the issue has since been intermittently occurring**

Attachments: 

![F7E77531-9D6C-4B5A-8547-E822A359535A](https://user-images.githubusercontent.com/127100536/223089209-af88a1cf-b3a4-4166-b279-9512b74e56e0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5913)

**Comment by abodea** [comment]
Hello, @PossiblyPeso thank you for adding this issue.
Please note that an issue regarding this was fixed https://github.com/mozilla-mobile/firefox-ios/issues/12857 and it will be included in the feature releases (soon)

**Comment by dnarcese** [comment]
@abodea can you confirm if #12857 fixes this issue?

**Comment by abodea** [comment]
Hello, @dnarcese I can confirm that I was not able to reproduce this issue while verifying https://github.com/mozilla-mobile/firefox-ios/issues/12857.
The only concern is that the bug was added on ` iPad Pro 12.9 5th gen, iPadOS 16.3.1` and the only iPad I have is iPad mini 5 (14.7.1) way smaller.
I think we can close this one too.

**Comment by PossiblyPeso** [comment]
Hi, @abodea  I have now updated to 110.2 and the bug is still present despite being marked as resolved on #12857. Just thought I'd let you know.
![6B730985-12FD-439D-A8B9-2B689FA9C55E](https://user-images.githubusercontent.com/127100536/224466582-2daf63cb-a983-426f-b286-f8bd3b204bc1.png)

**Comment by abodea** [comment]
Re-opening as I was able to reproduce on **v9000 (29660)** with **iPad mini 5 (14.7).**

I tried the following steps before but it didn't really happen:
1. Install FF
2. Switch to Private Browsing and open a few tabs there
3. Switch to Normal Browsing and open some tabs there too
4. Perform an interrupt by dragging on the right side, the App Bar/Status menu

https://user-images.githubusercontent.com/42831109/227224523-243dc019-22c0-47ce-9a81-555c8b27ea07.mov

**Comment by haarli** [comment]
Same problem. iPad Pro 2nd Gen, iOS 16.4, Firefox 111.2 (29672)

![IMG_0039](https://user-images.githubusercontent.com/5524896/230391582-eb21f031-50ff-4f38-9d2d-142d1de41cba.jpeg)

**Comment by canova** [comment]
Hey, this issue should be fixed with PR #13908 which landed in Firefox version 103. It should be in the Firefox Beta version now (on TestFlight). I can verify that the issue has been fixed on my machine. Could someone else maybe also check and see if it's fixed?

**Comment by lmarceau** [comment]
@canova the bug was reopened as explained [here](https://github.com/mozilla-mobile/firefox-ios/issues/13462#issuecomment-1481244480).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v114 (31032) with iPad Pro (16.4.1).
