### ISSUE TITLE
Firefox loads for a long time when attempting to sync, before crashing

### ISSUE THREAD

**Issue by ericswpark** [mozilla-mobile/firefox-ios#14279]
## Logs
You can help us by sending us either your crash logs or Firefox logs. Instructions on how to do this [here](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs).
[Archive.zip](https://github.com/mozilla-mobile/firefox-ios/files/11411420/Archive.zip)

Zipped up because GitHub doesn't allow `.ips` files

## Steps to reproduce
- Go into synced tabs page
![IMG_0390](https://user-images.githubusercontent.com/13326074/236602406-58f44f42-fd78-405c-abe0-288e2a592e13.jpeg)

- Pull down to refresh
- Firefox will display the loading spinner on the top (see below). This loading spinner will keep spinning. During this time, Firefox becomes unresponsive, and you cannot switch to anything else (such as tapping on "Tabs" or "Private" next to "Synced") or close out of the dialog entirely with the "Done" button. After about a minute or two of this going on, the actual behavior listed below occurs.
![IMG_0391](https://user-images.githubusercontent.com/13326074/236602408-3c1086d0-a92d-42f3-a1bf-6811190d9433.jpeg)

### Expected behavior

Syncs tabs and doesn't get unresponsive

### Actual behavior

Firefox crashes and returns the user to the springboard

### Device & build information
* Device: iPad Pro 12.9 5th-gen
* Build version: Firefox 112.2 (30158)

### Notes

This issue does not occur on my iPhone for some reason (14 Pro Max, same build version).

I did encounter some weird behavior from Firefox on my iPhone in the past, so I reinstalled it and it went away. I'm guessing this crash may have something to do with the device not being synced for quite some time. Is there anything in the sync process that could choke on devices that have "drifted" away from the sync data on the Firefox account?

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Documenting my findings so far:

  * The crash is easy to reproduce opening the Remote/Sync tabs from the SyncTab cell on JumpBack-In section of the homepage on iPad only. Is Watchdog termination crash where the memory and CPU increases until the apps get terminated for the user the UI just frozen.

The crash information provided in this ticket indicates the issue seems to be related to constraints not satisfied on iPad but if we open the TabTray for regular or private tabs and go to the Sync Tabs sections there is no crash. 

Option #1 investigate if we are missing any constraint or step when opening directly SyncTabs 

Investigating the reload process of the sync tabs we do in some cases 2 different request to get the information removing the call to profile.getClientsAndTabs() (second call to get the tabs info) doesn’t crash the app anymore but breaks the process of getting the latest tabs from other devices so it’s not a viable option.

Option #2 - Not viable right now is to refactor the refresh tabs process to avoid calling the API so often and investigate how this related to the apparent not satisfied constraint crash

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

I can’t reproduce this issue anymore, moving to QA Needed to verify

**Comment by ericswpark** [comment]
I can still reproduce this issue on the latest build of Firefox (115.1) on my iPad, but not on my iPhone. Like I said in my initial bug report, I think the client needs to have been offline for an extended period of time, such that it causes the sync process to use too much CPU/memory, getting it killed by the system (oom-killer equivalent or something on iOS?)


I checked the logs after the repro and crash and it looks like the system killed the process after it used too much CPU time:

```
CPU: 90 seconds cpu time over 94 seconds (96% cpu average), exceeding limit of 50% cpu over 180 seconds
```

I've attached the full log file below.

[Client.cpu_resource-2023-07-25-090850.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/12155882/Client.cpu_resource-2023-07-25-090850.ips.zip)

**Comment by ericswpark** [comment]
@lmarceau that's the strange part. Other than the `Client.cpu_resource-*.ips` file, no other crash logs were generated as far as I could tell.

**Comment by lmarceau** [comment]
@tarikeshaq would you mind taking a look at the logs and cpu resource files here? This seems to relate to the rust layer 🙏

**Comment by tarikeshaq** [comment]
Hi @ericswpark Thank you so much for getting the logs and I'm sorry you're experiencing this!

It's not clear to me how sync itself could cause the CPU resources we are seeing here, so this might be related to the remote tabs menu itself. Are able to reproduce this issue by tapping `Sync Now` in your settings menu (Hamburger menu -> Settings -> Sync Now) or does that complete successfully?

Additionally, there are foundational improvements coming to sync in 116 (releasing approx next week) That I hope should fix the problem you're facing!

re: The disconnected devices, that shouldn't be a problem, the logs we are seeing is Sync intentionally filtering out devices that are no longer active

**Comment by ericswpark** [comment]
Hi @tarikeshaq ,

The `Sync Now` button in the settings menu completes successfully. The problem only occurs in the remote tabs menu.

In fact, I now have the exact repro steps for it to crash:

- Top right tabs button -> Synced tab -> either pull down to refresh or click "Sync Tabs" -> **doesn't crash**
- "See all synced tabs" in Firefox Homepage -> goes straight to Synced tab, and **freezes**. When it freezes, the following is visible:
  - Either no tabs will be shown under the header, or
  - Tabs will be shown, but the favicons won't load in
- If it doesn't freeze, pulling down or refresh freezes it
- After about two minutes or so, the app crashes and drops the user back into the springboard.

Again, this is not reproducible on my iPhone – just my iPad. I'm not sure what the difference is, other than the fact that I've reinstalled the app on iPhone a while ago and maybe that cleared out whatever it is that is causing to crash. Or it could be just a bug that occurs on iPads.

Regarding the disconnected devices, I managed to solve the tabs showing up from disconnected devices by disconnecting and reconnecting my main laptop. My theory on that is that the sync got messed up when I migrated the Firefox installation on my Mac and it caused duplicate entries.

**Comment by lmarceau** [comment]
I just stumbled on some Xcode warnings that could possibly cause this issue? Xcode detected three different hang risks coming from some Sync Rust code. It's the first time Xcode warns me of those, I think it's worth looking into.

![Screenshot 2023-08-07 at 2 02 43 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/0cc696a4-d102-491e-b875-3125c26fcedc)
![Screenshot 2023-08-07 at 1 55 28 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/9b9c23ff-9845-4912-9eeb-8cce97b687a2)
![Screenshot 2023-08-07 at 1 55 37 PM](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/6220efae-11b4-472d-8345-2061ccb8415f)

**Comment by tarikeshaq** [comment]
Hmm those might be related and we should look into them, given that this hang and crash is only reproducible in the one surface (the remote tab menu) is a hint that it's possible that the surface is doing something with the main thread, when it's supposed to use a background thread there's some evidence in https://github.com/mozilla-mobile/firefox-ios/blob/9c85f82cac29794f3517af8418a94a13fea32f7d/Client/Frontend/Browser/Tabs/RemoteTabs/RemoteTabsPanel.swift#L257 

in 116.0 we changed the low-level implementation of the sync manager and the new one should always make sure not to do any work on the main thread

@ericswpark thank you so much for the details! 116.0 is released and rolling out, once you get the chance to upgrade it would be fantastic if you could verify if the hang/crash is fixed or is still there

**Comment by ericswpark** [comment]
@tarikeshaq updated to version 116.0 (33174) and I can still reproduce the hang and crash.

**Comment by joh4nd** [comment]
I have a similar problem.

iPad Air 2, ios 15.8.2. The synced tabs are displayed but cannot be entered; Firefox crashes.

An iPhone 7 also running ios 18.8.2 does not crash.

**Comment by joh4nd** [comment]
On version 124.2 (40108) I can now open sync'ed tabs via the icon on the upper left side of the GUI > switch to syncronized and choosing. It still crashes when trying to enter New Tab > go back to synced tabs via the show all sync'ed tabs.

**Comment by joh4nd** [comment]
https://github.com/mozilla-mobile/firefox-ios/issues/12067

**Comment by ericswpark** [comment]
This is still reproducible on Firefox 128.3 (43849).

**Comment by ericswpark** [comment]
Cannot reproduce on latest (140.3). Closing.
