### ISSUE TITLE
App on iOS freezes sometimes needing a force close to use again

### ISSUE THREAD

**Issue by shaunmeechan-abertay** [mozilla-mobile/firefox-ios#16018]
[Firefox.log](https://github.com/mozilla-mobile/firefox-ios/files/12321760/Firefox.log)
## Steps to reproduce
I’m not 100% sure but I have battery saver on and sometimes when I leave Firefox and return it has frozen. I only have 2 tabs open. I found locking the phone can cause it. Not found a good way to reproduce yet.

### Expected behavior
App resumes without issue. 

### Actual behavior
App freezes and I need to force close it. 
### Device & build information
* Device: iPhone XR, iOS16.6
* Build version: 116.1 (33291)
* First seen version: 116.1 (33291)
### Notes
Not sure if this counts as a crash but attached a crash log regardless.
Attachments: 

[Firefox.log](https://github.com/mozilla-mobile/firefox-ios/files/12321762/Firefox.log)
[Client.wakeups_resource-2023-08-11-084511.txt](https://github.com/mozilla-mobile/firefox-ios/files/12321763/Client.wakeups_resource-2023-08-11-084511.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7223)

**Comment by robertburke14** [comment]
This has also started happening to me within the last week or so. Very annoying. I lost an entire survey form I had filled out but not yet submitted. I updated the app with no resolution. Seems to happen when switching to another app.

**Comment by darren12345** [comment]
I came here to report this too. I don’t have battery saver on. It is possibly connected to how fast I go back to the iPhone Home Screen from FF and then reopen FF. If I do it fast, it seems to happen more frequently. I tried to reinstall FF, but that hasn’t helped. 
ios16.6, iPhone SE 2nd gen. Firefox 116.1 (33291).

**Comment by jtarchie** [comment]
This continues to happen with me.

v: 116.1
ios: 16.6

No noticeable pattern of usage I’ve determined. It seems to be after some usage. Don’t have a high number of tabs open, 3ish mostly.

The app doesn’t appear to crash. Because ios doesn’t try to restart it. I believe it is becoming unresponsive. Tap events don’t work, scrolling, etc. l

Since this using a web view on iOS, I’ve not determined if this happens with safari too. I’ll try it out for a day to see.

**Comment by darren12345** [comment]
> This continues to happen with me.
> 
> v: 116.1 ios: 16.6
> 
> No noticeable pattern of usage I’ve determined. It seems to be after some usage. Don’t have a high number of tabs open, 3ish mostly.
> 
> The app doesn’t appear to crash. Because ios doesn’t try to restart it. I believe it is becoming unresponsive. Tap events don’t work, scrolling, etc. l
> 
> Since this using a web view on iOS, I’ve not determined if this happens with safari too. I’ll try it out for a day to see.

I think if this was affecting Safari we'd see more noise about it. I very much suspect it's unique to FF.

**Comment by OrlaM** [comment]
@tarikeshaq I think this issue from Sentry could be related to this. Looks like something is happening when opening the places database to cause the app to hang for more than 2 seconds.
https://mozilla.sentry.io/issues/4391975373/events/eacb8312b7514654a8e8fefb9803dad7/

We don't get hang data from production, only beta so hard to say for sure if this is the underlying issue.

**Comment by fowl2** [comment]
This is happening to me on the iOS 17 public beta.

**Comment by tarikeshaq** [comment]
@OrlaM Yeah there is a possible hang there - we either move the opening of the database out of the main thread or change the inner `writer.sync` to `writer.async`. But you're correct in that it's hard to tell if this is the underlying issue here, a hint that this is the issue is a hang on the homescreen before any topsites load. Regardless, we should fix the places db opening hang. I'll get a fix going for that

**Comment by shaunmeechan-abertay** [comment]
Just happened again to me. Opened a tab this morning but haven’t used app until just there. I was able to tap where the URL bar would be and the keyboard opened but nothing happened. Weirdly when I restarted the app the tab I was on became the homepage rather than what used to be there and I had no option to try recover the tab

**Comment by darren12345** [comment]
For the first time, this just happened to me while I was using Firefox, not opening it again. Same symptom as above: the keyboard opened but that was it.

**Comment by jtarchie** [comment]
I have not experienced it at all today. It seems either I've not recreated it or it has resolved.

**Comment by shaunmeechan-abertay** [comment]
Updated to version 116.2 (33536) this morning and still having the issue.

**Comment by shaunmeechan-abertay** [comment]
Further update. I had this just happen to me while I was actively using the app. I loaded a new page then the app froze up but again I could press fields that take an input and the keyboard would open. The input field wouldn’t have the indicator icon and text wouldn’t enter. This makes me wonder if it has something to do with page loading rather than coming back from idle? I checked for a crash report but can’t see one.

**Comment by t-p-white** [comment]
This happened for me today while trying to use auto complete on a form, please see attached log. I believe the freeze occurred at log `2023-08-19 13:31:55.542`.
[Firefox copy.log](https://github.com/mozilla-mobile/firefox-ios/files/12385884/Firefox.copy.log)

**Comment by lmarceau** [comment]
Hello! There's a new v116.3 release that is available that should help with the freeze issue. Please let us know if this version helps with the problem or not 🙏

**Comment by darren12345** [comment]
> Hello! There's a new v116.3 release that is available that should help with the freeze issue. Please let us know if this version helps with the problem or not 🙏

I don't *think* I've experienced a crash since updating. Will continue to monitor. Thanks.

**Comment by shaunmeechan-abertay** [comment]
> Hello! There's a new v116.3 release that is available that should help with the freeze issue. Please let us know if this version helps with the problem or not 🙏

I've been using the app since that release and haven't seen the issue yet. Looks to me that it's now fixed so will close the issue. If it reappears I'll reopen this/make a new one.
