### ISSUE TITLE
117.0 Crashing on iOS 14

### ISSUE THREAD

**Issue by luigigorlero** [mozilla-mobile/firefox-ios#16209]
## Logs
[Client-2023-08-29-184030.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/12473395/Client-2023-08-29-184030.ips.zip)

## Steps to reproduce
Firefox crashes at launch after latest update

### Device & build information
* Device: iPhone XR
* Build version: 14.4.2 (18D70)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7304)

**Comment by Umberwolf** [comment]
I also have the same problem of Firefox crashing at launch.
[Client-2023-09-04-083035.000.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/12517643/Client-2023-09-04-083035.000.ips.zip)

Device: iPhone 12 mini
Build version: 14.2.1

**Comment by ddiggles** [comment]
Same here, crashes straight back to springboard

Device: iPhone 7 Plus
Build version: 14.3

I'm jailbroken, but it crashes in both JB and non-JB states.

**Comment by lmarceau** [comment]
Hello! Thank you for reporting this issue. We're investigating it, and it seems to be related to the OS version (between 14.0 and 14.4), if you upgrade your OS to a more recent version it should fix the problem. In the meantime, we'll continue to figure out a solution. Thank you!

**Comment by Amzd** [comment]
For jailbroken device (since iOS 14 is the most recent jb version so you can't update iOS);

Use AppStore++ tweak to downgrade to Firefox 116.4

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v117.3 (34056) with iPad mini 5 (14.7.1). 
I had no crashes, please note that this is the only device available with 14.x.x

**Comment by ddiggles** [comment]
This is not fixed, still crashes immediately back to springboard on open, iOS 14.3

**Comment by Amzd** [comment]
Fixed on 117.3

Note that the update rolls out gradually and earlier today when I tried latest version was still crashing but now I was able to update and see the fix. Thank you so much.
