### ISSUE TITLE
"Close All Tabs" crashes app intermittently

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#16810]
## Steps to reproduce
1. Open a website.
1. Tab tabs button. Open a new (normal) tab.
1. Open a website on the new tab.
1. Tab tabs button again.
1. Tap trash can icon 🗑️.
1. Tap "Close All Tabs". 

The steps are reproducible manually and via the XCUITest `testCloseAllTabsUndo()`. The same crash is shown on both iPhone and iPad.
https://github.com/mozilla-mobile/firefox-ios/blob/main/Tests/XCUITests/TopTabsTest.swift#L121

I have not reproduced the issue on private tabs.

### Expected behavior
Tabs are closed. The homepage with the "Undo" button is displayed.

### Actual behavior
The app crashes about 1/3 of the time after tapping "Close All Tabs". When I open the app again, the tabs are preserved.

### Device & build information
* Device: iOS simulator iOS 17.0. Physical iPad device.
* OS: 17.0 (Not an issue on 16.x)
* Build version: 9000 (35105)
* First seen version: Oct 11ish?
    1. Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/1740517/49ec0ddb-f3ed-4e7f-b334-3130cb32ea2a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7554)

**Comment by clarmso** [comment]
@yoanarios Is there any work related to this issue? If not I can close this ticket. 😄

**Comment by yoanarios** [comment]
The fix has been merged and I moved the ticket to QA needed if is not reproducible anymore I think we are good to close it

**Comment by yoanarios** [comment]
Reopening the issue because the crash is reproducible again. 

This issue was first fixed in this [commit](https://github.com/mozilla-mobile/firefox-ios/commit/bc4267d8404bea1750a08ad3129dab8b9d3340d6) and I cannot reproduce the crash anymore but in the current main branch (commit sha: b8062cde711b34b3188f5c80379d44d1b37d8d09) is reproducible again so I will investigate the possible causes

**Comment by clarmso** [comment]
In the meanwhile, `DesktopModeTestsIpad/testLongPressReload` (iPad only) and `DesktopModeTestsIpad/testLongPressReload` at "Close All Tabs".

**Comment by yoanarios** [comment]
@clarmso do you mean the iPad tests are also failing?
I'm able to reproduce the crash using `testLongPressReload` test for iPhone it looks like the original fix was just a partial one that didn't account for these steps but the remaining crash is harder to reproduce than the original so I'm still investigating

**Comment by clarmso** [comment]
> @clarmso do you mean the iPad tests are also failing? 
Yes, the corresponding test for iPad fails in the same way too, but the test for iPad isn't a part of smoke test running on Bitrise.

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

The crash is still happening but it is harder to reproduce manually. It is recommended to run testLongPressReload repeatedly to test possible fixes. 
The cause seems to be the same inconsistency in JumpBackIn Viewmodel/Adaptor when all tabs are deleted

**Comment by clarmso** [comment]
I could mitigate the intermittent failures on `testLongPressReload()` by opening a new tab first. 😑 
https://github.com/mozilla-mobile/firefox-ios/pull/17133

**Comment by data-sync-user** [comment]
➤ Dianna Smith commented:

Looks like introduced in Fx120.0 and will be reverted in 120.3

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Orla Mitchell Can you please confirm how we should update status of this ticket? Revert was merged today for hotfix but I wasn’t entirely clear if we should update to QA Needed for validation etc. Thank you

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, please note that I tried on v120.3 (36471) with the following devices:

  * iPhone 13 Pro Max (15.7.1) - I had 50 tries of close all tabs but FF never crashed
  * iPhone SE (16.6) - At least 25+ tries of close all tabs but FF never crashed
  * iPhone 14 (17) - FF crashes at least 2 times out of 10, I had like 50 tries and ~every 10 tries I had 2 crashes.

Adding this information for when we will need to verify this issue.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Small update, I was able to reproduce this issue on v9000 (36834) with iPhone 15 Pro Max (17.1.2), and iPhone 15+ (17.0.2).
The issue is still intermittent, but I could repro it ~3 times out of 10 tries.

**Comment by dragosb01** [comment]
The steps affected by this crash for testLongPressReload, testCloseAllTabs and testCloseAllTabsUndo tests have been disabled until the issue will be fixed.

**Comment by dragosb01** [comment]
@clarmso @yoanarios test3AutocompleteDeletingChars automated test started to fail on the same steps from this issue, causing the app to crash.

**Comment by data-sync-user** [comment]
➤ Dragos Bigu commented:

matt i am reopening this issue because it is reproducing on our automation tests (test3AutocompleteDeletingChars). cc Clare So Yoana Rios Diaz

**Comment by dragosb01** [comment]
Disabled testRemoveAllTabsButtonRecentlyClosedHistory and workaround for test3AutocompleteDeletingChars and testTopSitesRemoveAllExceptPinnedClearPrivateData tests to avoid failures caused by this crash

**Comment by abodea** [comment]
I was able to reproduce this issue 2 times out of 10 tries with the iPhone 15 Pro (17.4.1) on v125 (40715).
CC: @afurlan-firefox 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/839f2a04-4c99-4d3d-bdbb-4196beaa155f

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Nishant Bhasin Norberto Andres Furlan as fyi

**Comment by Nachtpfoetchen** [comment]
I experience this exact behavior on 143.2 on ios 26.0.1 on the iphone 12 mini.
