### ISSUE TITLE
Focus: string export still broken in automation

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/firefox-ios#19507]
CC @isabelrios 

I tested locally #19407, and it was working without issues. To my surprise, automation today was still broken.

I have no clue how or why, but my usual local clone works without issues, if I start with a fresh clone it's broken.

```
git clone https://github.com/mozilla-mobile/firefox-ios --depth 1
cd firefox-ios
./checkout.sh
./focus-ios/focus-ios-tests/tools/export-strings.sh
tail focus-ios/export-strings.log
```

You should see a build error at the end of the log file.

I tried to diff the two folders but it's completely useless (too many differences). I also tried to run `bootstrap.sh`, but I still get an error.

What's even weirder is that the error in automation is different from the local one.

Automation (15.0.1)

```
2024-04-02T12:50:46.2134730Z /Users/runner/work/focusios-l10n/focusios-l10n/code_repo/focus-ios/Widgets/Widgets.swift:8:8: error: no such module 'Widget'
2024-04-02T12:50:46.2135970Z import Widget
2024-04-02T12:50:46.2136290Z        ^
```

Local (15.3)

```
firefox-ios/focus-ios/Blockzilla.xcodeproj: warning: DEFINES_MODULE was set, but no umbrella header could be found to generate the module map (in target 'RustMozillaAppServices' from project 'Blockzilla')
2024-04-02 15:26:15.262 xcodebuild[78420:3601348] Writing error result bundle to /var/folders/7k/613lfl692dq22n6q952h_syw0000gp/T/
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8799)

**Comment by flodolo** [comment]
Correction: the error is the same locally. 

```
firefox-ios/focus-ios/Widgets/Widgets.swift:8:8: error: no such module 'Widget'
import Widget
       ^
```

I've also tried to open the project in XCode and it builds normally, but the export via command line still doesn't work.

I have no clue how I got to a state in which my older clone works.

**Comment by isabelrios** [comment]
I can reproduce the failure in latest main too :( I thought it was fixed with latest PR, I will check if there is something after it that could be affecting how it is working.

**Comment by flodolo** [comment]
> I thought it was fixed with latest PR

As mentioned, the weirdest thing is that I have a local clone, updated to the latest commit, where the script still works 🤔 
Clearly we're hitting some weird edge case.

**Comment by isabelrios** [comment]
yeah, agree...

**Comment by flodolo** [comment]
One more discovery: I renamed the folder with my local working clone, then repeated the steps in first commit to clone and export. To my surprise, it works. If I repeat the process in any other path on disk, it fails.

So, there must be some cache somewhere on my device, not in the clone itself, that allows the export script to work.

**Comment by dicarobinho** [comment]
@isabelrios @flodolo 

I still reproduce it too but yea, only from terminal. I will keeping looking into it. Hope to get a fix asap.

**Comment by isabelrios** [comment]
Thanks @dicarobinho !

**Comment by nbhasin2** [comment]
@dicarobinho is it broken while running the export strings.sh
-  https://github.com/mozilla-mobile/firefox-ios/blob/main/focus-ios/focus-ios-tests/tools/export-strings.sh ?
cc @isabelrios

**Comment by isabelrios** [comment]
yes, we see the same error in the logs.

Actually @flodolo I think the import is also broken with same issue :( we have not had a PR to import strings for a while. I run the import-strings.sh script and I can see the Widget error...

**Comment by flodolo** [comment]
> Actually @flodolo I think the import may be broken too with same issue :( we have not had a PR to import strings for a while. I run the import-strings.sh script and I can see the Widget error...

I don't see errors in the logs. Also, since Focus doesn't get new strings, there has been little activity
https://github.com/mozilla-l10n/focusios-l10n/commits/main/

**Comment by isabelrios** [comment]
yeah, the github action does not show errors, either, looks like the script finishes correctly, I saw that locally too. However if you open the import-strings.log file, the error is there.
At least as you say, there are not strings coming in

**Comment by flodolo** [comment]
Seems to be broken in a different way now

```
2024-04-06 18:19:44.859 xcodebuild[33480:6105293] Writing error result bundle to /var/folders/7k/613lfl692dq22n6q952h_syw0000gp/T/ResultBundle_2024-06-04_18-19-0044.xcresult
xcodebuild: error: Could not resolve package dependencies:
  Couldn’t check out revision ‘937dce13c2600cc42112c480d04f84899e08e9cc’:
    fatal: bad object refs/remotes/origin/armcknight/feat/launch-profile-data-in-app-start-spans
  binary target 'Sentry' could not be mapped to an artifact with expected name 'Sentry'

```

**Comment by dicarobinho** [comment]
@nbhasin2 yes, it is broken when running https://github.com/mozilla-mobile/firefox-ios/blob/main/focus-ios/focus-ios-tests/tools/export-strings.sh and is the same error **no such module 'Widget'**. Tried to figure it out but unfortunately no success.

<img width="1087" alt="Screenshot 2024-04-08 at 12 02 29" src="https://github.com/mozilla-mobile/firefox-ios/assets/61138287/f93e56c2-2d08-4e5f-a5ac-f34aed59d795">

**Comment by dicarobinho** [comment]
@flodolo hmmm, I'm not getting that error.

**Comment by isabelrios** [comment]
Neither do I, I'm still seeing the Widget error

**Comment by flodolo** [comment]
Have you tried running the `checkout.sh` command again? For me, it took a while (and downloaded a Sentry package).

**Comment by dicarobinho** [comment]
@flodolo I did it and it worked well. 

cd firefox-ios ->  ./checkout.sh

**Comment by flodolo** [comment]
Weird. There seems to be a recent update to Sentry, so I'm surprised I'm the only one getting that error now
https://github.com/mozilla-mobile/firefox-ios/pull/19665
