### ISSUE TITLE
Blank page is displayed after fresh install and force close

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#20831]
**Steps to reproduce**

1. Fresh install FF.
1. Open FF and force close the app.
1. Reopen FF.

**Expected behavior**
FF homepage is displayed.

**Actual behavior**
A blank page is displayed.

Device & build information

* Device: iPhone 15 (17.5)
* Build version: v128 (43061)
* First seen version: v128 (43061)

Notes
Please note that this issue doesn't repro on v128 (42985) beta 8.
This issue is also reproducible with tab tray refactor enabled.
This issue doesn't reproduce with FF update.

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/151131988/b854048f-545d-494a-b79c-4fc8a2246efd

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9406)

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Fix available on release/v128

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

fix now available on main

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(43298) with iPhone 14 Pro Max (iOS 16.2).

**Comment by DianaABarladeanu** [comment]
This issue is still reproducible on v9000 (43516), also with this scenario: open a tab, return to homepage and force close the app. When reopening the app, a blank page is displayed.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v129 (44023), with iPhone 15 (17.5).

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Moving this issue back to in progress because it reproduces on  Firefox v129.1 build

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Note: this hasn’t yet been merged into the 129 build. My understanding is we are waiting for the next weekly release. cc Alina Moldovan Norberto Andres Furlan Donal Meehan

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

Matt Reagan Judging from Github branches/merges this ticket is Done right?

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Sophie Amin This bug has regressed a few times in the past so it would probably be good to confirm with QA (cc Andrei Bodea), but AFAIK this should now be fully resolved. The change to make the session read/writes synchronous should’ve corrected this.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v131 (45403), with iPhone 15 (17.5).
