### ISSUE TITLE
[Edit Bookmark][Edit folder] "Save In" section heading is sticky and moves across the page along with scroll down

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#29695]
**Steps to Reproduce:**

1. On FF, sign in with an account with 10+ folders and bookmarks. 
1. From the three dots menu, select Bookmarks. 
1. Tap the Edit button. Reach the Edit Folder/bookmark screen. 
1. View the “Save in” section and tap on Bookmarks folder to unfold the options. 
1. Scroll down through the options. 

**Expected Result:**

“Save in” section heading is not overlapping any of the bookmark fields as we scroll. 

**Actual Result:**

“Save in” section heading is overlapping the folder fields. 

**Device & Build Information:**

* Device: iPhone 14 Pro max (iOS 26)
* Build version: v143.2 (62039)

:information_source: **Reference Person**

[+@Foxbolts+](https://github.com/Foxbolts)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-13693)

**Comment by ananyashreesharma** [comment]
This issue appears to be fixed in the latest Fennec development build but still exists in the official Firefox app.

Testing Details:
Device: iPhone 12 (iOS 26.0.1)

Fennec development build: Working correctly (no overlap issue)
<img width="300" height="600" alt="Image" src="https://github.com/user-attachments/assets/3ee3484a-3e59-4526-bce4-985892adb5db" />

Official Firefox ios app: v144.0 - Still has the "SAVE IN" header overlap
<img width="300" height="600" alt="Image" src="https://github.com/user-attachments/assets/4678480d-3976-4d7d-b180-0b31734aa287" />

Question:
Is this fix already implemented in the development branch but not yet released to the App Store? The behavior is different between Fennec and the official app.
Could you confirm if this fix is scheduled for the next release? @cyndichin @Foxbolts @data-sync-user

**Comment by Foxbolts** [comment]
Hey @ananyashreesharma - thanks for the heads up. While this particular issue hasn't necessarily been worked on, it is possible it may have been resolved unintentionally as a result of some other work. I'm noticing it seems resolved on v141.1, possible as a result of b522efe (which may be iOS 26 only)

Miruna Curtean - would you mind testing this?

**Comment by hkarmoush** [comment]
I'd like to work on this issue. I'm interested in understanding the root cause and implementing a fix.

**Comment by Foxbolts** [comment]
Hey @hkarmoush, I have assigned the issue to you. From my previous comment, I would double-check to see if this issue is reproducible (and reporting back your findings) before investigating a solution.

**Comment by hkarmoush** [comment]
Hey @Foxbolts, thanks for the assignment! I dug into this and wanted to share what I found before jumping into a fix.

**Reproduction**

The overlap is still reproducible, but it's version-dependent:
- **iOS 15–25:** the "SAVE IN" header still floats and overlaps the folder rows while scrolling. Bug is live here.
- **iOS 26+:** looks fine, no overlap.

That lines up with what @ananyashreesharma saw (fixed in Fennec dev but broken in the App Store build) and with your hunch about b522efe.

**Root cause**

Both `EditBookmarkViewController` and `EditFolderViewController` build their table view with a version gate:

```swift
if #available(iOS 26.0, *) {
    UITableView(frame: .zero, style: .insetGrouped)
} else {
    UITableView() // .plain
}
```

That gate came in with b522efe (the iOS 26 rounded-corners work). The catch is that `.plain`-style tables pin their section headers to the top as you scroll, which is exactly the "SAVE IN overlapping the rows" behavior. `.insetGrouped` (and `.grouped`) headers scroll away with the content instead, so iOS 26 got fixed for free while everything below it kept the old plain-style pinning.

**Proposed fix**

Drop the version gate and use `.insetGrouped` on all versions in both view controllers. It fixes the pinning everywhere and makes pre-26 match the appearance you already ship on iOS 26. I checked the surrounding code and it looks side-effect-safe: both VCs already override the table background with the themed color, the header spacer and separators behave the same, and the iOS 26 path is unchanged.

The one visible trade-off is that on iOS 15–25 the cells would pick up the inset/rounded grouped look instead of the current edge-to-edge plain style. That's unavoidable since the bug *is* the plain-style header pinning, but I wanted to flag it in case design has an opinion. If we'd rather keep pre-26 closer to its current look, using `.grouped` instead of `.insetGrouped` also kills the overlap without the rounded/inset cells.

Happy to go with whichever direction you prefer. Let me know and I'll put up a PR.
