### ISSUE TITLE
Tab switching and removing lag

### ISSUE THREAD

**Issue by Christian-ASG** [mozilla-mobile/firefox-ios#30497]
### Device & build information
* Device: iPhone 11 iOS 26.1
* Build version: idk what you meancwith build version but i assume this (attachment)
* First seen version: Today but i installed the app yesterday
### i cannot upload a screen recording because it fails to upload

Attachments:

<img width="414" height="896" alt="Image" src="https://github.com/user-attachments/assets/b7763722-72e5-40d0-82fc-5de0e3169422" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-14066)

**Comment by janbrasna** [comment]
Possibly duplicate of:
- https://github.com/mozilla-mobile/firefox-ios/issues/30404
- https://github.com/mozilla-mobile/firefox-ios/issues/30322

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

I am going to tag Laurie Marceau as she is amazing at finding hangs etc.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

I think you’re referring to Carson Ramsden 😆 but I can have a look in case I find something ahah

**Comment by Nerd2k** [comment]
I can verify this bug.
I have 15-20 tabs with different websites open permanently. The app gets very laggy after a few hours of being open/in the background. I have it set up so that my tabs get restored on opening of the app. When the app gets laggy after a few hours, I have to close it and reopen it, it’s now quick and responsive again - until after a few hours when it progressively gets slower and slower again.

Device: iPhone 15 Pro
iOS version: iOS 18.6.2 (22G100)
Firefox version: Firefox 145.0 (63787)

It first happened a few updates ago, when there was something about the tab tray announced or something. Don’t quote me on this though. But I do know that it’s like maximum 5 updates ago when it first happened.

**Comment by janbrasna** [comment]
@Christian-ASG If you have videos to upload and it's bigger than GitHub limits you can also upload it to e.g. Google Drive or YouTube or any similar host (I have used https://streamable.com before but their expiration limits for free users can be too short for this use) and share the link here.

@Nerd2k Just to verify, the lag in this ticket relates to switching tabs via Tab Tray, does that sound like the issue you're seeing?

There have been changes in the past few releases, has any of that improved for you when you update to v147 and newer? Thanks!

**Comment by Nerd2k** [comment]
@janbrasna yes that was exactly the issue I was seeing. After my post in this ticket, the bug had stayed active for a couple of releases without any improvement. But then at some point it vanished.
I don’t know whether it improved over a few release cycles and progressively got better or whether it vanished suddenly from one release to the next. I didn’t track that.
But I can verify that it’s now gone for me since a couple of weeks. So it has been either fixed at some point or code has changed in a way that stopped the bug.
Thanks for the follow up!

**Comment by janbrasna** [comment]
That's great to hear! Yes, the tracking ticket #30322 lists the layout improvements for v147.0 that were being worked on throughout December that then shipped around January 12 for everyone. 

Hopefully that will resolve all the issues folks were running into, but everyone's usage patterns are different so feel free to chime in if you still observe any woes in that area when running the latest version — thanks for the reports!

**Comment by kelimuttu** [comment]
We still get [reports](https://support.mozilla.org/en-US/questions/1537077#answer-1803448) about this from users on SUMO.

**Comment by jlennox** [comment]
I still encounter this issue frequently, and restart firefox several times per day.
